//WOMEN PRODUCTS
const womenProducts = [
    {
        _id: '1',
        name: 'Menns',
        image: '/images/w1.svg',
        description:
          'High top fashion shoes',
        brand: 'nike',
        category: 'New',
        price: 999.99,
        countInStock: 0,
        rating: 3.5,
        numReviews: 12,
      }, 
      {
        _id: '2',
        name: 'Sportees',
        image: '/images/w2.svg',
        description:
          'Exotic joggers- yellow',
        brand: 'nike',
        category: 'New',
        price: 229.99,
        countInStock: 10,
        rating: 3.5,
        numReviews: 12,
      },
      {
        _id: '3',
        name: 'Sketchers',
        image: '/images/w3.svg',
        description:
          'Exotic sport shoes',
        brand: 'nike',
        category: 'New',
        price: 629.99,
        countInStock: 0,
        rating: 2.7,
        numReviews: 12,
      },
       {
        _id: '4',
        name: 'Sportees',
        image: '/images/w4.svg',
        description:
          'Exotic joggers',
        brand: 'nike',
        category: 'New',
        price: 229.99,
        countInStock: 5,
        rating: 2.7,
        numReviews: 12,
      },
      {
        _id: '5',
        name: 'Papsae',
        image: '/images/w5.svg',
        description:
          'Mens fashion shoes',
        brand: 'nike',
        category: 'New',
        price: 729.99,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '6',
        name: 'Fashion Sneakers',
        image: '/images/w6.svg',
        description:
          'lightweight sneakers',
        brand: 'puma',
        category: 'New',
        price: 349.99,
        countInStock: 7,
        rating: 3.5,
        numReviews: 10,
      },
      {
        _id: '7',
        name: 'Canvas sneakers',
        image: '/images/w7.svg',
        description:
          'Sneaker sport shoes',
        brand: 'vans',
        category: 'New',
        price: 399.99,
        countInStock: 11,
        rating: 5,
        numReviews: 12,
      },
      {
        _id: '8',
        name: 'Leather Boots',
        image: '/images/w8.svg',
        description:'Exotic jungle boots',
        brand: 'Addidas',
        category: 'New',
        price: 929.99,
        countInStock: 5,
        rating: 3,
        numReviews: 12,
      },
      {
        _id: '9', 
        image: '/images/w9.svg',
        name: 'Merrell',
        description:'Outdoor, fashion shoes',
        brand: 'Nike',
        category: 'New',
        price: 149.79,
        countInStock: 5,
        rating: 2.5,
        numReviews: 12,
      },
      {
        _id: '10',
        image: '/images/w10.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '11',
        image: '/images/w11.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '12',
        image: '/images/w12.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '13',
        image: '/images/w13.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '14',
        image: '/images/w14.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '15',
        image: '/images/w15.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '16',
        image: '/images/w16.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '17',
        image: '/images/w17.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '18',
        image: '/images/w18.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '19',
        image: '/images/w19.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '20',
        image: '/images/w20.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
  ];

  //XCLUSIVE PRODUCTS
  const WomenXclusive = [
    {
        _id: '1',
        name: 'Menns',
        image: '/images/wx1.svg',
        description:
          'High top fashion shoes',
        brand: 'nike',
        category: 'New',
        price: 999.99,
        countInStock: 0,
        rating: 3.5,
        numReviews: 12,
      },
      {
        _id: '2',
        name: 'Sportees',
        image: '/images/wx2.svg',
        description:
          'Exotic joggers- yellow',
        brand: 'nike',
        category: 'New',
        price: 229.99,
        countInStock: 10,
        rating: 3.5,
        numReviews: 12,
      },
      {
        _id: '3',
        name: 'Sketchers',
        image: '/images/wx3.svg',
        description:
          'Exotic sport shoes',
        brand: 'nike',
        category: 'New',
        price: 629.99,
        countInStock: 0,
        rating: 2.7,
        numReviews: 12,
      },
       {
        _id: '4',
        name: 'Sportees',
        image: '/images/wx4.svg',
        description:
          'Exotic joggers',
        brand: 'nike',
        category: 'New',
        price: 229.99,
        countInStock: 5,
        rating: 2.7,
        numReviews: 12,
      },
      {
        _id: '5',
        name: 'Papsae',
        image: '/images/wx5.svg',
        description:
          'Mens fashion shoes',
        brand: 'nike',
        category: 'New',
        price: 729.99,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '6',
        name: 'Fashion Sneakers',
        image: '/images/wx6.svg',
        description:
          'lightweight sneakers',
        brand: 'puma',
        category: 'New',
        price: 349.99,
        countInStock: 7,
        rating: 3.5,
        numReviews: 10,
      },
      {
        _id: '7',
        name: 'Canvas sneakers',
        image: '/images/wx7.svg',
        description:
          'Sneaker sport shoes',
        brand: 'vans',
        category: 'New',
        price: 399.99,
        countInStock: 11,
        rating: 5,
        numReviews: 12,
      },
      {
        _id: '8',
        name: 'Leather Boots',
        image: '/images/wx8.svg',
        description:'Exotic jungle boots',
        brand: 'Addidas',
        category: 'New',
        price: 929.99,
        countInStock: 5,
        rating: 3,
        numReviews: 12,
      },
      {
        _id: '9', 
        image: '/images/wx9.svg',
        name: 'Merrell',
        description:'Outdoor, fashion shoes',
        brand: 'Nike',
        category: 'New',
        price: 149.79,
        countInStock: 5,
        rating: 2.5,
        numReviews: 12,
      },
      {
        _id: '10',
        image: '/images/wx10.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '11',
        image: '/images/wx11.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '12',
        image: '/images/wx12.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '13',
        image: '/images/wx13.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '14',
        image: '/images/wx14.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '15',
        image: '/images/wx15.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '16',
        image: '/images/wx16.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '17',
        image: '/images/wx17.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '18',
        image: '/images/wx18.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '19',
        image: '/images/wx19.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '20',
        image: '/images/wx20.svg',
        name: 'Men Sneakers',
        description:
        'High top sneakers',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      
  ];
  //NEW PRODUCTS
  const WnewProducts = [
    {
      _id: '1',
      name: 'Menns',
      image: '/images/n1.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'Sportees',
      image: '/images/n2.svg',
      description:
        'Exotic joggers- yellow',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 10,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '3',
      name: 'Sketchers',
      image: '/images/n3.svg',
      description:
        'Exotic sport shoes',
      brand: 'nike',
      category: 'New',
      price: 629.99,
      countInStock: 0,
      rating: 2.7,
      numReviews: 12,
    },
     {
      _id: '4',
      name: 'Sportees',
      image: '/images/n4.svg',
      description:
        'Exotic joggers',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 5,
      rating: 2.7,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Papsae',
      image: '/images/n5.svg',
      description:
        'Mens fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 729.99,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
    {
      _id: '6',
      name: 'Fashion Sneakers',
      image: '/images/n6.svg',
      description:
        'lightweight sneakers',
      brand: 'puma',
      category: 'New',
      price: 349.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '7',
      name: 'Canvas sneakers',
      image: '/images/n7.svg',
      description:
        'Sneaker sport shoes',
      brand: 'vans',
      category: 'New',
      price: 399.99,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '8',
      name: 'Leather Boots',
      image: '/images/n8.svg',
      description:'Exotic jungle boots',
      brand: 'Addidas',
      category: 'New',
      price: 929.99,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '9', 
      image: '/images/n9.svg',
      name: 'Merrell',
      description:'Outdoor, fashion shoes',
      brand: 'Nike',
      category: 'New',
      price: 149.79,
      countInStock: 5,
      rating: 2.5,
      numReviews: 12,
    },
    {
      _id: '10',
      image: '/images/n10.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
  ];

  //HARD DRIVE    
  const relatedProducts = [
    {
      _id: '1',
      name: 'Menns',
      image: '/images/hd1.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'Sportees',
      image: '/images/hd2.svg',
      description:
        'Exotic joggers- yellow',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 10,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '3',
      name: 'Sketchers',
      image: '/images/hd3.svg',
      description:
        'Exotic sport shoes',
      brand: 'nike',
      category: 'New',
      price: 629.99,
      countInStock: 0,
      rating: 2.7,
      numReviews: 12,
    },
     {
      _id: '4',
      name: 'Sportees',
      image: '/images/hd4.svg',
      description:
        'Exotic joggers',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 5,
      rating: 2.7,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Papsae',
      image: '/images/hd5.svg',
      description:
        'Mens fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 729.99,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
    {
      _id: '6',
      name: 'Fashion Sneakers',
      image: '/images/hd6.svg',
      description:
        'lightweight sneakers',
      brand: 'puma',
      category: 'New',
      price: 349.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '7',
      name: 'Canvas sneakers',
      image: '/images/hd7.svg',
      description:
        'Sneaker sport shoes',
      brand: 'vans',
      category: 'New',
      price: 399.99,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '8',
      name: 'Leather Boots',
      image: '/images/hd8.svg',
      description:'Exotic jungle boots',
      brand: 'Addidas',
      category: 'New',
      price: 929.99,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '9', 
      image: '/images/hd9.svg',
      name: 'Merrell',
      description:'Outdoor, fashion shoes',
      brand: 'Nike',
      category: 'New',
      price: 149.79,
      countInStock: 5,
      rating: 2.5,
      numReviews: 12,
    },
    {
      _id: '10',
      image: '/images/hd10.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
  ]



  //MEN PRODUCTS
  const MenProducts = [
    {
      _id: '1',
      name: 'Menns',
      image: '/images/m1.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'Sportees',
      image: '/images/m2.svg',
      description:
        'Exotic joggers- yellow',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 10,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '3',
      name: 'Sketchers',
      image: '/images/m3.svg',
      description:
        'Exotic sport shoes',
      brand: 'nike',
      category: 'New',
      price: 629.99,
      countInStock: 0,
      rating: 2.7,
      numReviews: 12,
    },
     {
      _id: '4',
      name: 'Sportees',
      image: '/images/m4.svg',
      description:
        'Exotic joggers',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 5,
      rating: 2.7,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Papsae',
      image: '/images/m5.svg',
      description:
        'Mens fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 729.99,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
    {
      _id: '6',
      name: 'Fashion Sneakers',
      image: '/images/m6.svg',
      description:
        'lightweight sneakers',
      brand: 'puma',
      category: 'New',
      price: 349.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '7',
      name: 'Canvas sneakers',
      image: '/images/m7.svg',
      description:
        'Sneaker sport shoes',
      brand: 'vans',
      category: 'New',
      price: 399.99,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '8',
      name: 'Leather Boots',
      image: '/images/m8.svg',
      description:'Exotic jungle boots',
      brand: 'Addidas',
      category: 'New',
      price: 929.99,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '9', 
      image: '/images/m9.svg',
      name: 'Merrell',
      description:'Outdoor, fashion shoes',
      brand: 'Nike',
      category: 'New',
      price: 149.79,
      countInStock: 5,
      rating: 2.5,
      numReviews: 12,
    },
    {
      _id: '10',
      image: '/images/m10.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '11',
      image: '/images/m11.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '12',
      image: '/images/m12.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '13',
      image: '/images/m13.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '14',
      image: '/images/m14.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '15',
      image: '/images/m15.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '16',
      image: '/images/m10.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '17',
      image: '/images/m17.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '18',
      image: '/images/m18.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '19',
      image: '/images/m19.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '20',
      image: '/images/m20.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
  ]
  //MEN PRODUCTS
   const MenXclusive = [
    {
      _id: '1',
      name: 'Menns',
      image: '/images/mx1.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'Sportees',
      image: '/images/mx2.svg',
      description:
        'Exotic joggers- yellow',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 10,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '3',
      name: 'Sketchers',
      image: '/images/mx3.svg',
      description:
        'Exotic sport shoes',
      brand: 'nike',
      category: 'New',
      price: 629.99,
      countInStock: 0,
      rating: 2.7,
      numReviews: 12,
    },
     {
      _id: '4',
      name: 'Sportees',
      image: '/images/mx4.svg',
      description:
        'Exotic joggers',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 5,
      rating: 2.7,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Papsae',
      image: '/images/mx5.svg',
      description:
        'Mens fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 729.99,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
    {
      _id: '6',
      name: 'Fashion Sneakers',
      image: '/images/mx6.svg',
      description:
        'lightweight sneakers',
      brand: 'puma',
      category: 'New',
      price: 349.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '7',
      name: 'Canvas sneakers',
      image: '/images/mx7.svg',
      description:
        'Sneaker sport shoes',
      brand: 'vans',
      category: 'New',
      price: 399.99,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '8',
      name: 'Leather Boots',
      image: '/images/mx8.svg',
      description:'Exotic jungle boots',
      brand: 'Addidas',
      category: 'New',
      price: 929.99,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '9', 
      image: '/images/mx9.svg',
      name: 'Merrell',
      description:'Outdoor, fashion shoes',
      brand: 'Nike',
      category: 'New',
      price: 149.79,
      countInStock: 5,
      rating: 2.5,
      numReviews: 12,
    },
    {
      _id: '10',
      image: '/images/mx10.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '1',
      image: '/images/mx11.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '12',
      image: '/images/mx12.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '13',
      image: '/images/mx13.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '14',
      image: '/images/mx14.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '15',
      image: '/images/mx15.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '16',
      image: '/images/mx16.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '17',
      image: '/images/mx17.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '18',
      image: '/images/mx18.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '19',
      image: '/images/mx19.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '20',
      image: '/images/mx20.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
  ]


//MNEW PRODUCTS
const MnewProducts = [
  {
    _id: '1',
    name: 'Menns',
    image: '/images/mn1.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sportees',
    image: '/images/mn2.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Sketchers',
    image: '/images/mn3.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
   {
    _id: '4',
    name: 'Sportees',
    image: '/images/mn4.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Papsae',
    image: '/images/mn5.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Fashion Sneakers',
    image: '/images/mn6.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '7',
    name: 'Canvas sneakers',
    image: '/images/mn7.svg',
    description:
      'Sneaker sport shoes',
    brand: 'vans',
    category: 'New',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Leather Boots',
    image: '/images/mn8.svg',
    description:'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9', 
    image: '/images/mn9.svg',
    name: 'Merrell',
    description:'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/images/mn10.svg',
    name: 'Men Sneakers',
    description:
    'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];



  //KIDS PRODUCTS
  const kidsProducts = [
    {
      _id: '1',
      name: 'Menns',
      image: '/images/k1.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'Sportees',
      image: '/images/k2.svg',
      description:
        'Exotic joggers- yellow',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 10,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '3',
      name: 'Sketchers',
      image: '/images/k3.svg',
      description:
        'Exotic sport shoes',
      brand: 'nike',
      category: 'New',
      price: 629.99,
      countInStock: 0,
      rating: 2.7,
      numReviews: 12,
    },
     {
      _id: '4',
      name: 'Sportees',
      image: '/images/k4.svg',
      description:
        'Exotic joggers',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 5,
      rating: 2.7,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Papsae',
      image: '/images/k5.svg',
      description:
        'Mens fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 729.99,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
    {
      _id: '6',
      name: 'Fashion Sneakers',
      image: '/images/k6.svg',
      description:
        'lightweight sneakers',
      brand: 'puma',
      category: 'New',
      price: 349.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '7',
      name: 'Canvas sneakers',
      image: '/images/k7.svg',
      description:
        'Sneaker sport shoes',
      brand: 'vans',
      category: 'New',
      price: 399.99,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '8',
      name: 'Leather Boots',
      image: '/images/k8.svg',
      description:'Exotic jungle boots',
      brand: 'Addidas',
      category: 'New',
      price: 929.99,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '9', 
      image: '/images/k9.svg',
      name: 'Merrell',
      description:'Outdoor, fashion shoes',
      brand: 'Nike',
      category: 'New',
      price: 149.79,
      countInStock: 5,
      rating: 2.5,
      numReviews: 12,
    },
    {
      _id: '10',
      image: '/images/k10.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '11',
      image: '/images/k11.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '12',
      image: '/images/k12.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '13',
      image: '/images/k13.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '14',
      image: '/images/k14.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '15',
      image: '/images/k15.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '16',
      image: '/images/k16.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '17',
      image: '/images/k17.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '18',
      image: '/images/k18.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '19',
      image: '/images/k19.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '20',
      image: '/images/k20.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
  ]

  const KnewProducts = [
    {
      _id: '1',
      name: 'Menns',
      image: '/images/kn1.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'Sportees',
      image: '/images/kn2.svg',
      description:
        'Exotic joggers- yellow',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 10,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '3',
      name: 'Sketchers',
      image: '/images/kn3.svg',
      description:
        'Exotic sport shoes',
      brand: 'nike',
      category: 'New',
      price: 629.99,
      countInStock: 0,
      rating: 2.7,
      numReviews: 12,
    },
     {
      _id: '4',
      name: 'Sportees',
      image: '/images/kn4.svg',
      description:
        'Exotic joggers',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 5,
      rating: 2.7,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Papsae',
      image: '/images/kn5.svg',
      description:
        'Mens fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 729.99,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
    {
      _id: '6',
      name: 'Fashion Sneakers',
      image: '/images/kn6.svg',
      description:
        'lightweight sneakers',
      brand: 'puma',
      category: 'New',
      price: 349.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '7',
      name: 'Canvas sneakers',
      image: '/images/kn7.svg',
      description:
        'Sneaker sport shoes',
      brand: 'vans',
      category: 'New',
      price: 399.99,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '8',
      name: 'Leather Boots',
      image: '/images/kn8.svg',
      description:'Exotic jungle boots',
      brand: 'Addidas',
      category: 'New',
      price: 929.99,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '9', 
      image: '/images/kn9.svg',
      name: 'Merrell',
      description:'Outdoor, fashion shoes',
      brand: 'Nike',
      category: 'New',
      price: 149.79,
      countInStock: 5,
      rating: 2.5,
      numReviews: 12,
    },
    {
      _id: '10',
      image: '/images/kn10.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
  ];


  const KidsXclusive = [
    {
      _id: '1',
      name: 'Menns',
      image: '/images/kx1.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'Sportees',
      image: '/images/kx2.svg',
      description:
        'Exotic joggers- yellow',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 10,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '3',
      name: 'Sketchers',
      image: '/images/kx3.svg',
      description:
        'Exotic sport shoes',
      brand: 'nike',
      category: 'New',
      price: 629.99,
      countInStock: 0,
      rating: 2.7,
      numReviews: 12,
    },
     {
      _id: '4',
      name: 'Sportees',
      image: '/images/kx4.svg',
      description:
        'Exotic joggers',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 5,
      rating: 2.7,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Papsae',
      image: '/images/kx5.svg',
      description:
        'Mens fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 729.99,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
    {
      _id: '6',
      name: 'Fashion Sneakers',
      image: '/images/kx6.svg',
      description:
        'lightweight sneakers',
      brand: 'puma',
      category: 'New',
      price: 349.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '7',
      name: 'Canvas sneakers',
      image: '/images/kx7.svg',
      description:
        'Sneaker sport shoes',
      brand: 'vans',
      category: 'New',
      price: 399.99,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '8',
      name: 'Leather Boots',
      image: '/images/kx8.svg',
      description:'Exotic jungle boots',
      brand: 'Addidas',
      category: 'New',
      price: 929.99,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '9', 
      image: '/images/kx9.svg',
      name: 'Merrell',
      description:'Outdoor, fashion shoes',
      brand: 'Nike',
      category: 'New',
      price: 149.79,
      countInStock: 5,
      rating: 2.5,
      numReviews: 12,
    },
    {
      _id: '10',
      image: '/images/kx10.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '11',
      image: '/images/kx11.svg', 
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '12',
      image: '/images/kx12.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '13',
      image: '/images/kx13.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '14',
      image: '/images/kx14.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '15',
      image: '/images/kx15.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '16',
      image: '/images/kx16.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '17',
      image: '/images/kx17.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '18',
      image: '/images/kx18.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '19',
      image: '/images/kx19.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '20',
      image: '/images/kx20.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
  ]

  //New products 

  const newproducts = [
    {
      _id: '1',
      image: '/images/productsA.svg',
      name: 'Men Sneakers',
      description:
      'High top sneakers',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '2', 
      image: '/images/productsB.svg',
      name: 'Merrell',
      description:
      'Outdoor, fashion shoes',
      brand: 'Nike',
      category: 'New',
      price: 149.79,
      countInStock: 5,
      rating: 2.5,
      numReviews: 12,
    },
    {
      _id: '3',
      name: 'Leather Boots',
      image: '/images/productsC.svg',
      description:
        'Exotic jungle boots',
      brand: 'Addidas',
      category: 'New',
      price: 929.99,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '4',
      name: 'Canvas sneakers',
      image: '/images/productsD.svg',
      description:
        'Sneaker sport shoes',
      brand: 'vans',
      category: 'New',
      price: 399.99,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Fashion Sneakers',
      image: '/images/productsE.svg',
      description:
        'lightweight sneakers',
      brand: 'puma',
      category: 'New',
      price: 349.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '6',
      name: 'Papsae',
      image: '/images/productsF.svg',
      description:
        'Mens fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 729.99,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
    {
      _id: '7',
      name: 'Sportees',
      image: '/images/productsG.svg',
      description:
        'Exotic joggers',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 5,
      rating: 2.7,
      numReviews: 12,
    },
    {
      _id: '8',
      name: 'Sketchers',
      image: '/images/productsH.svg',
      description:
        'Exotic sport shoes',
      brand: 'nike',
      category: 'New',
      price: 629.99,
      countInStock: 0,
      rating: 2.7,
      numReviews: 12,
    },
    {
      _id: '9',
      name: 'Sportees',
      image: '/images/productsI.svg',
      description:
        'Exotic joggers- yellow',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 10,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '10',
      name: 'Menns',
      image: '/images/productsJ.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '11',
      name: 'Sportees',
      image: '/images/productsK.svg',
      description:
        'Exotic joggers- yellow',
      brand: 'nike',
      category: 'New',
      price: 229.99,
      countInStock: 10,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '12',
      name: 'Menns',
      image: '/images/productsL.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '13',
      name: 'Menns',
      image: '/images/productsM.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '14',
      name: 'Menns',
      image: '/images/productsN.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '15',
      name: 'Menns',
      image: '/images/productsO.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '16',
      name: 'Menns',
      image: '/images/productsP.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '17',
      name: 'Menns',
      image: '/images/productsQ.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '18',
      name: 'Menns',
      image: '/images/productsR.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '19',
      name: 'Menns',
      image: '/images/productsS.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: '20',
      name: 'Menns',
      image: '/images/productsT.svg',
      description:
        'High top fashion shoes',
      brand: 'nike',
      category: 'New',
      price: 999.99,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
  ]
  
  const featuredProducts = [
    {
      _id: '1',
      image: '/images/featuredA.svg',
      name: 'Nike air jordan',
      description:
      'Nike Air Jordan 2021:Snipe In Grand Style',
      brand: 'Nike',
      category: 'New',
      price: 189.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
        _id: '2',
        image: '/images/featuredB.svg',
        name: 'Nike air max',
        description:
        'Nike Air Max 2021:Show Off In Grand Style',
        brand: 'Nike',
        category: 'New',
        price: 189.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '3', 
        image: '/images/featuredC.svg',
        name: 'Sportees Heelpeak AE0-2: 2021',
        description:
        'Snipe in comfort: Get yours Now',
        brand: 'Sportess',
        category: 'New',
        price: 600.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '4', 
        image: '/images/featuredD.svg',
        name: 'Sportees GoRun B5-2: 2021',
        description:
        'Snipe in comfort: Get yours Now',
        brand: 'Sportess',
        category: 'New',
        price: 600.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '5', 
        image: '/images/featuredE.svg',
        name: 'Sportees SnipeFeet G6-A: 2021',
        description:
        'Snipe in comfort: Get yours Now',
        brand: 'Sportess',
        category: 'New',
        price: 600.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '6', 
        image: '/images/brandBG.svg',
        name: 'Lebron N-Walk Collection: 2021', 
        description:
        'Snipe in comfort: Get yours Now',
        brand: 'Sportess', 
        category: 'New',
        price: 800.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '7', 
        image: '/images/featuredG.svg',
        name: 'Lebron N-Walk HL-43: 2021',
        description:
        'Snipe in comfort: Get yours Now',
        brand: 'Sportess',
        category: 'New',
        price: 800.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '8', 
        image: '/images/featuredH.svg',
        name: 'Lebron N-Walk HL-43: 2021',
        description:
        'Snipe in comfort: Get yours Now',
        brand: 'Sportess',
        category: 'New',
        price: 800.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '9', 
        image: '/images/featuredI.svg',
        name: 'Lebron N-Walk HL-43: 2021',
        description:
        'Snipe in comfort: Get yours Now',
        brand: 'Sportess',
        category: 'New',
        price: 800.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '10', 
        image: '/images/featuredJ.svg',
        name: 'Nike Air Max 2021',
        description:
        'Snipe in comfort: Get yours Now',
        brand: 'Sportess',
        category: 'New',
        price: 800.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '11', 
        image: '/images/featuredK.svg',
        name: 'Nike Air Max 2021',
        description:
        'Snipe in comfort: Get yours Now',
        brand: 'Sportess',
        category: 'New',
        price: 800.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '12', 
        image: '/images/featuredL.svg',
        name: 'Nike Air Max 2021',
        description:
        'Snipe in comfort: Get yours Now',
        brand: 'Sportess',
        category: 'New',
        price: 800.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '13', 
        image: '/images/featuredM.svg',
        name: 'New Balance-Fresh Foam Roav',
        description:
        'Snipe in comfort: Get yours Now',
        brand: 'Sportess',
        category: 'New',
        price: 400.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
  ]

  module.exports = {
    womenProducts,
    WomenXclusive,
    WnewProducts,
    relatedProducts,
    MenProducts,
    MenXclusive,
    MnewProducts,
    kidsProducts,
    KnewProducts,
    KidsXclusive,
    newproducts,
    featuredProducts,
  }